<Project Sdk="Microsoft.NET.Sdk" TreatAsLocalProperty="Configuration">

  <PropertyGroup>
    <Configuration>Release</Configuration>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="PrimesValidate/**" />
  </ItemGroup>

</Project>
